### ISSUE TITLE
add org error at channel update (single host mode).

### ISSUE THREAD

**Issue by bruce3401** [davidkhala/delphi-fabric#1]
你好，在Ubuntu16.04( 阿里云ECS) 上按照README的步骤执行，遇到了如下错误：
```
Error: No public port '7051/tcp' published for AMContainerName
Error: No public port '7053/tcp' published for AMContainerName
```
之后log继续输出，运行了configtxlator。又输出如下错误：
```
[2017-12-04 16:13:52.395] [ERROR] test-configtxlator - addOrg Error: No identity has been assigned to this client
    at Client._getSigningIdentity (/root/delphi-fabric/node_modules/fabric-client/lib/Client.js:1150:11)
    at Channel.getChannelConfig (/root/delphi-fabric/node_modules/fabric-client/lib/Channel.js:516:36)
    at Channel.initialize (/root/delphi-fabric/node_modules/fabric-client/lib/Channel.js:143:15)
    at api.channelUpdate.then (/root/delphi-fabric/app/testConfigtxlator.js:39:18)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
请问有什么解决方案吗？或者是操作错误？

**Comment by davidkhala** [comment]
亲爱的朋友，动态添加组织的那部分有点年久失修了，我有空会更新那部分的，欢迎加微信davidkhala

**Comment by bruce3401** [comment]
谢谢你 我就持续关注这个repo

**Comment by davidkhala** [comment]
@dyllanwli 我最近开始着手修这个库了，请关注

**Comment by davidkhala** [comment]
不知道加组织的部分还需不需要帮助？我先关了

**Comment by bruce3401** [comment]
抱歉 很久前就解决了[LOL] 谢谢~
